PITCH_ASPECT_RATIO = 68 / 105
PITCH_OUTER_MARGIN = 18
PITCH_GOAL_DEPTH = 12

PLAYER_CARD_MIN_WIDTH = 42
PLAYER_CARD_MAX_WIDTH = 104
PLAYER_CARD_MIN_HEIGHT = 44
PLAYER_CARD_MAX_HEIGHT = 54
PLAYER_CARD_LINE_GAP_RATIO = 0.84

BOARD_MINIMUM_WIDTH = 360
BOARD_MINIMUM_HEIGHT = 540
INSPECTOR_MINIMUM_WIDTH = 260
BENCH_MINIMUM_WIDTH = 160
SIDE_PANEL_MAXIMUM_WIDTH = 260
SPLITTER_BOARD_RATIO = 0.58
SPLITTER_INSPECTOR_RATIO = 0.42
SPLITTER_HANDLE_WIDTH = 8

COMPACT_SECTION_SPACING = 8
COMPACT_PANEL_PADDING = 10
