PITCH_ASPECT_RATIO = 68 / 105
PITCH_OUTER_MARGIN = 18
PITCH_GOAL_DEPTH = 12

PLAYER_CARD_MIN_WIDTH = 42
PLAYER_CARD_MAX_WIDTH = 104
PLAYER_CARD_MIN_HEIGHT = 44
PLAYER_CARD_MAX_HEIGHT = 54
PLAYER_CARD_LINE_GAP_RATIO = 0.84

BOARD_MINIMUM_WIDTH = 420
BOARD_MINIMUM_HEIGHT = 660
INSPECTOR_MINIMUM_WIDTH = 280
SPLITTER_BOARD_RATIO = 0.65
SPLITTER_INSPECTOR_RATIO = 0.35
SPLITTER_HANDLE_WIDTH = 8

COMPACT_SECTION_SPACING = 8
COMPACT_PANEL_PADDING = 10
