SURFACE = "#ffffff"
BACKGROUND = "#f5f6f8"
BORDER = "#e4e7ec"
BORDER_STRONG = "#d0d5dd"
TEXT_PRIMARY = "#1f2937"
TEXT_SECONDARY = "#667085"
TEXT_MUTED = "#98a2b3"

PRIMARY = "#2563eb"
PRIMARY_SOFT = "#eef6ff"

POSITIVE = "#027a48"
POSITIVE_BG = "#ecfdf3"
POSITIVE_BORDER = "#abefc6"

NEUTRAL = "#475467"
NEUTRAL_BG = "#f2f4f7"
NEUTRAL_BORDER = "#d0d5dd"

WARNING = "#b54708"
WARNING_BG = "#fffaeb"
WARNING_BORDER = "#fedf89"

CRITICAL = "#b42318"
CRITICAL_BG = "#fef3f2"
CRITICAL_BORDER = "#fecdca"

UNAVAILABLE = "#6941c6"
UNAVAILABLE_BG = "#f4f3ff"
UNAVAILABLE_BORDER = "#d9d6fe"

UNKNOWN = "#344054"
UNKNOWN_BG = "#f8fafc"
UNKNOWN_BORDER = "#e4e7ec"

STATUS_COLORS = {
    "positive": (POSITIVE_BG, POSITIVE_BORDER, POSITIVE),
    "neutral": (NEUTRAL_BG, NEUTRAL_BORDER, NEUTRAL),
    "warning": (WARNING_BG, WARNING_BORDER, WARNING),
    "critical": (CRITICAL_BG, CRITICAL_BORDER, CRITICAL),
    "unavailable": (UNAVAILABLE_BG, UNAVAILABLE_BORDER, UNAVAILABLE),
    "unknown": (UNKNOWN_BG, UNKNOWN_BORDER, UNKNOWN),
}
