from ht_coach_app.core.version import APP_BASE_NAME, APP_DISPLAY_NAME, APP_VERSION


APP_NAME = APP_BASE_NAME
WINDOW_TITLE = APP_DISPLAY_NAME
WINDOW_MINIMUM_WIDTH = 1280
WINDOW_MINIMUM_HEIGHT = 720
SIDEBAR_WIDTH = 220
